@api = http://localhost:4000/api/carreras

GET {{api}}

###
POST {{api}}
Content-Type: application/json

{
    "nombreCarrera": "TI",
    "idFacPer": 5
}

###
GET {{api}}/7

###
POST {{api}}/byCareerName 
Content-Type: application/json

{
    "nombreCarrera": "TI"
}

###
DELETE {{api}}/6

###
PUT {{api}}/9
Content-Type: application/json

{
  "nombreCarrera": "REDES",
  "idFacPer": 3
}